config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about", as: 'about'

  resources :users, only: %i[index show edit]
  resources :books, only: %i[index show edit create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_one_attached :profile_image

  def get_profile_image
    (profile_image.attached?)? profile_image: 'no_image.jpeg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
    else
      @books = Book.all
      render 'index'
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h1>New book</h1>
<%= form_with model:book,local:true do |f| %>
  <div>
    <%= f.label :Title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :Opinion %><br>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<script src="fade_in.js"></script>
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render 'users/info', user: current_user %>
      <%= render 'form', book: @book %>
    </div>
    <div class="col-8 offset-1">
      <h1>Books</h1>
      <% @books.each do |book| %>
        <div class="card mb-3 fade-in fade-in-up scroll-in" style="width: 19rem">
          <div><%= image_tag book.user.get_profile_image %></div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to book.title,book %></h5>
            <p class="card-text"><%= book.body %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render 'users/info', user: @user %>
      <%= render 'form', book: @book %>
    </div>
    <div class="col-8 offset-1">
      <h1>Book detail</h1>
      <table class="table">
        <tr>
          <td width="20%">
            <%= image_tag @user.get_profile_image, size:'100x100' %><br>
            <%= link_to @user.name, @user %>
          </td>
          <td width="20%"><%= @books.title %></td>
          <td><%= @books.body %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container mt-5">
  <div class="row">
    <h1 class="mx-auto">Welcome to <strong><i class="fas fa-book"></i>Bookers!</strong></h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-5">
  <h1>Welcome to <strong><i class="fas fa-book"></i>Bookers!!</strong></h1>
  <p>
    In <strong><i class="fas fa-book"></i>Bookers</strong>,<br>
    you can share and exchange your opinions , inpressions , and emotions<br>
    about various books!
  </p>
  <button type="button" class="btn btn-info"><%= link_to 'Log in',new_user_session_path %></button>
  <button type="button" class="btn btn-success"><%= link_to 'Sign_up',new_user_registration_path %></button>
</div>

app/views/layouts/_footer.html.erb
<div class='container mt-5'>
  <div class='row'>
  	<div class='mx-auto'>
  	  <p>CopyRight Infratop.inc</p>
  	</div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/"><span>Bookers</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user), class: "nav-link text-light" do %>
            <i class="fas fa-home"></i> Home
          <% end %>
        </li>
        <li>
          <%= link_to users_path, class: "nav-link text-light" do %>
            <i class="fas fa-users"></i> Users
          <% end %>
        </li>
        <li>
          <%= link_to books_path, class: "nav-link text-light" do %>
            <i class="fas fa-book-open"></i> Books
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i> Log out
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to root_path, class: "nav-link text-light" do %>
            <i class="fas fa-home"></i> Home
          <% end %>
        </li>
        <li>
          <%= link_to about_path, class: "nav-link text-light" do %>
           <i class="fas fa-link"></i> About
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
            <i class="fas fa-user-plus"></i> Sign up
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path, class: "nav-link text-light" do %>
            <i class="fas fa-sign-in-alt"></i> Log in
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_info.html.erb
<h1>User info</h1>
<table>
  <tr>
    <th>name</th>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <th>introduction</th>
    <td><%= user.introduction %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/9d9107d4e2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>-->
    <header>
      <%= render 'layouts/header' %>
    </header>
    <%= yield %>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<h1>User info</h1>
<%= image_tag user.get_profile_image, size:'100x100' %>
<table class="table">
  <tr>
    <th>name</th>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <th>introduction</th>
    <td><%= user.introduction %></td>
  </tr>
</table>
<div class="row">
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render 'info', user: current_user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-8 offset-1">
      <h1>Users</h1>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image, size:'75x75' %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render 'info', user: @user %>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-8 offset-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th width="15%"></th>
            <th width="35%">Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= image_tag @user.get_profile_image, size:'75x75' %></td>
              <td><%= link_to book.title, book %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>